version: '2'
services:

    aikido-web:
        build: docker/web
        restart: always
        links:
            - phpminds-api-db:mysql
        ports:
            - 4180:80
        env_file:
            - .env
        environment:
            XDEBUG_CONFIG: "remote_host=${HOST_IP}"
        volumes:
            - "nfsmount_phpminds_api:/var/www/html"

    phpminds-api-db:
        image: mysql:5.7.22
        restart: always
        ports:
            - 4106:3306
        env_file:
          - .env
        volumes:
            - "nfsmount_phpminds_api:/var/www/html"

volumes:
    nfsmount_phpminds_api:
        driver: local
        driver_opts:
            type: nfs
            o: addr=host.docker.internal,rw,nolock,hard,nointr,nfsvers=3
            device: ":${WEB_APP_PATH}"
